on:
  pull_request:
    types: [opened, synchronize, closed]
  push:
    branches: [main]

env:
  TZ: Asia/Tokyo
  ref: ${{ github.head_ref || github.ref_name }}
  github_pages_branch_name: github-pages
  github_pages_branch_dir: docs/${{ github.head_ref || github.ref_name }}
  github_pages_branch_url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.head_ref || github.ref_name }}
  artifact_jest_coverage: jest-coverage
  artifact_storybook_coverage: storybook-coverage
  artifact_storybook_static: storybook-static
  artifact_lcov_report: lcov-report

# concurrency:
#   group: ${{ github.head_ref || github.ref_name }}-${{ github.workflow }}
#   cancel-in-progress: true

jobs:
  debug:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: echo "${{ toJson(github) }}"

  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: node
      - uses: actions/cache@v3
        id: cache_node_modules
        with:
          path: "**/node_modules"
          key: node_modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
        if: ${{ steps.cache_node_modules.outputs.cache-hit != 'true' }}

  jest:
    needs: [setup]
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: node
      - uses: actions/cache@v3
        id: cache_node_modules
        with:
          path: "**/node_modules"
          key: node_modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/package-lock.json') }}
      - run: npx jest --colors --coverage --coverageDirectory coverage --passWithNoTests
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_jest_coverage }}
          path: coverage/coverage-final.json

  storybook:
    needs: [setup]
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: node
      - uses: actions/cache@v3
        id: cache_node_modules
        with:
          path: "**/node_modules"
          key: node_modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/package-lock.json') }}
      - run: npx storybook build
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_storybook_static }}
          path: storybook-static
      - run: npx playwright install --with-deps chromium
      - run: >
          npx concurrently -k -s first -n "storybook,test" -c "magenta,blue"
          "npx http-server storybook-static --port 6006 --silent"
          "wait-on tcp:6006 && npx test-storybook --coverage --browsers chromium"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_storybook_coverage }}
          path: coverage/storybook/coverage-storybook.json

  lcov:
    needs: [jest, storybook]
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.artifact_jest_coverage }}
          path: coverage
        continue-on-error: true
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.artifact_storybook_coverage }}
          path: coverage
        continue-on-error: true
      - run: npx nyc report -t coverage --reporter=lcov --report-dir coverage
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_lcov_report }}
          path: coverage/lcov-report

  github-pages:
    needs: [lcov]
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.github_pages_branch_name }}
      - run: rm -rf ${{ env.github_pages_branch_dir }}
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.artifact_lcov_report }}
          path: ${{ env.github_pages_branch_dir }}/lcov-report
        continue-on-error: true
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.artifact_storybook_static }}
          path: ${{ env.github_pages_branch_dir }}/storybook
        continue-on-error: true
      - name: Git commit and push
        run: |
          cat << EOF > commit-message
          ${{ env.ref }} (${{ github.event_name }})
          Triggered via ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} ${{ (github.event.after != '' && format('(Commit {0})', github.event.after)) || '' }}
          EOF
          git config --local user.name "${{ github.workflow }}"
          git config --local user.email ""
          git add docs
          git commit -F commit-message
          git push origin ${{ env.github_pages_branch_name }}

  pr-comment:
    needs: [github-pages]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Create PR comment
        run: |
          cat << EOF >> pr-comment
          ## Github Pages
          - Storybook  
          ${{ env.github_pages_branch_url }}/storybook
          - Coverage  
          ${{ env.github_pages_branch_url }}/lcov-report
          EOF
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: github-pages
          path: pr-comment
